// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go
//
// Generated by this command:
//
//	mockgen -package cache -source cache.go -destination=cache_mock.go ShardCache
//

// Package cache is a generated GoMock package.
package cache

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	store "github.com/cadence-workflow/shard-manager/service/sharddistributor/store"
)

// MockShardCache is a mock of ShardCache interface.
type MockShardCache struct {
	ctrl     *gomock.Controller
	recorder *MockShardCacheMockRecorder
	isgomock struct{}
}

// MockShardCacheMockRecorder is the mock recorder for MockShardCache.
type MockShardCacheMockRecorder struct {
	mock *MockShardCache
}

// NewMockShardCache creates a new mock instance.
func NewMockShardCache(ctrl *gomock.Controller) *MockShardCache {
	mock := &MockShardCache{ctrl: ctrl}
	mock.recorder = &MockShardCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShardCache) EXPECT() *MockShardCacheMockRecorder {
	return m.recorder
}

// GetExecutor mocks base method.
func (m *MockShardCache) GetExecutor(ctx context.Context, namespace, executorID string) (*store.ShardOwner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutor", ctx, namespace, executorID)
	ret0, _ := ret[0].(*store.ShardOwner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecutor indicates an expected call of GetExecutor.
func (mr *MockShardCacheMockRecorder) GetExecutor(ctx, namespace, executorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutor", reflect.TypeOf((*MockShardCache)(nil).GetExecutor), ctx, namespace, executorID)
}

// GetShardAssignments mocks base method.
func (m *MockShardCache) GetShardAssignments(namespace string) (store.AssignmentSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShardAssignments", namespace)
	ret0, _ := ret[0].(store.AssignmentSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShardAssignments indicates an expected call of GetShardAssignments.
func (mr *MockShardCacheMockRecorder) GetShardAssignments(namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShardAssignments", reflect.TypeOf((*MockShardCache)(nil).GetShardAssignments), namespace)
}

// GetShardOwner mocks base method.
func (m *MockShardCache) GetShardOwner(ctx context.Context, namespace, shardID string) (*store.ShardOwner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShardOwner", ctx, namespace, shardID)
	ret0, _ := ret[0].(*store.ShardOwner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShardOwner indicates an expected call of GetShardOwner.
func (mr *MockShardCacheMockRecorder) GetShardOwner(ctx, namespace, shardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShardOwner", reflect.TypeOf((*MockShardCache)(nil).GetShardOwner), ctx, namespace, shardID)
}

// Subscribe mocks base method.
func (m *MockShardCache) Subscribe(namespace string) (<-chan struct{}, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", namespace)
	ret0, _ := ret[0].(<-chan struct{})
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockShardCacheMockRecorder) Subscribe(namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockShardCache)(nil).Subscribe), namespace)
}
