package metered

// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/metered.tmpl
// gowrap: http://github.com/hexdigest/gowrap

import (
	"context"

	"github.com/cadence-workflow/shard-manager/common/clock"
	"github.com/cadence-workflow/shard-manager/common/log"
	"github.com/cadence-workflow/shard-manager/common/metrics"
	"github.com/cadence-workflow/shard-manager/service/sharddistributor/store"
)

// meteredStore implements store.Store interface instrumented with metrics.
type meteredStore struct {
	base
	wrapped store.Store
}

// NewStore creates a new instance of Store with metrics.
func NewStore(
	wrapped store.Store,
	metricClient metrics.Client,
	logger log.Logger,
	timeSource clock.TimeSource,
) store.Store {
	if wrapped == nil {
		return nil
	}
	return &meteredStore{
		wrapped: wrapped,
		base: base{
			metricClient: metricClient,
			logger:       logger,
			timeSource:   timeSource,
		},
	}
}

func (c *meteredStore) AssignShards(ctx context.Context, namespace string, request store.AssignShardsRequest, guard store.GuardFunc) (err error) {
	op := func() error {
		err = c.wrapped.AssignShards(ctx, namespace, request, guard)
		return err
	}

	err = c.call(metrics.ShardDistributorStoreAssignShardsScope, op, metrics.NamespaceTag(namespace))
	return
}

func (c *meteredStore) DeleteAssignedStates(ctx context.Context, namespace string, executorIDs []string, guard store.GuardFunc) (err error) {
	op := func() error {
		err = c.wrapped.DeleteAssignedStates(ctx, namespace, executorIDs, guard)
		return err
	}

	err = c.call(metrics.ShardDistributorStoreDeleteAssignedStatesScope, op, metrics.NamespaceTag(namespace))
	return
}

func (c *meteredStore) DeleteExecutors(ctx context.Context, namespace string, executorIDs []string, guard store.GuardFunc) (err error) {
	op := func() error {
		err = c.wrapped.DeleteExecutors(ctx, namespace, executorIDs, guard)
		return err
	}

	err = c.call(metrics.ShardDistributorStoreDeleteExecutorsScope, op, metrics.NamespaceTag(namespace))
	return
}

func (c *meteredStore) DeleteShardStats(ctx context.Context, namespace string, shardIDs []string, guard store.GuardFunc) (err error) {
	op := func() error {
		err = c.wrapped.DeleteShardStats(ctx, namespace, shardIDs, guard)
		return err
	}

	err = c.call(metrics.ShardDistributorStoreDeleteShardStatsScope, op, metrics.NamespaceTag(namespace))
	return
}

func (c *meteredStore) DrainHosts(ctx context.Context, namespace string, hosts []store.DrainedHost) (err error) {
	op := func() error {
		err = c.wrapped.DrainHosts(ctx, namespace, hosts)
		return err
	}

	err = c.call(metrics.ShardDistributorStoreDrainHostsScope, op, metrics.NamespaceTag(namespace))
	return
}

func (c *meteredStore) DrainShards(ctx context.Context, namespace string, shardIDs []string) (err error) {
	op := func() error {
		err = c.wrapped.DrainShards(ctx, namespace, shardIDs)
		return err
	}

	err = c.call(metrics.ShardDistributorStoreDrainShardsScope, op, metrics.NamespaceTag(namespace))
	return
}

func (c *meteredStore) GetDrainedHosts(ctx context.Context, namespace string) (da1 []store.DrainedHost, err error) {
	op := func() error {
		da1, err = c.wrapped.GetDrainedHosts(ctx, namespace)
		return err
	}

	err = c.call(metrics.ShardDistributorStoreGetDrainedHostsScope, op, metrics.NamespaceTag(namespace))
	return
}

func (c *meteredStore) GetDrainedShards(ctx context.Context, namespace string) (sa1 []string, err error) {
	op := func() error {
		sa1, err = c.wrapped.GetDrainedShards(ctx, namespace)
		return err
	}

	err = c.call(metrics.ShardDistributorStoreGetDrainedShardsScope, op, metrics.NamespaceTag(namespace))
	return
}

func (c *meteredStore) GetExecutorState(ctx context.Context, namespace string, executorID string) (e1 store.ExecutorState, err error) {
	op := func() error {
		e1, err = c.wrapped.GetExecutorState(ctx, namespace, executorID)
		return err
	}

	err = c.call(metrics.ShardDistributorStoreGetExecutorStateScope, op, metrics.NamespaceTag(namespace))
	return
}

func (c *meteredStore) GetState(ctx context.Context, namespace string) (np1 *store.NamespaceState, err error) {
	op := func() error {
		np1, err = c.wrapped.GetState(ctx, namespace)
		return err
	}

	err = c.call(metrics.ShardDistributorStoreGetStateScope, op, metrics.NamespaceTag(namespace))
	return
}

func (c *meteredStore) RecordHeartbeat(ctx context.Context, namespace string, executorID string, state store.HeartbeatState) (err error) {
	op := func() error {
		err = c.wrapped.RecordHeartbeat(ctx, namespace, executorID, state)
		return err
	}

	err = c.call(metrics.ShardDistributorStoreRecordHeartbeatScope, op, metrics.NamespaceTag(namespace))
	return
}

func (c *meteredStore) RecordShardStatistics(ctx context.Context, namespace string, executorID string, assignmentModRevision int64, statistics map[string]store.ShardStatistics) (err error) {
	op := func() error {
		err = c.wrapped.RecordShardStatistics(ctx, namespace, executorID, assignmentModRevision, statistics)
		return err
	}

	err = c.call(metrics.ShardDistributorStoreRecordShardStatisticsScope, op, metrics.NamespaceTag(namespace))
	return
}

func (c *meteredStore) RecordShardStatisticsBatch(ctx context.Context, namespace string, updates []store.ExecutorShardStatistics) (err error) {
	op := func() error {
		err = c.wrapped.RecordShardStatisticsBatch(ctx, namespace, updates)
		return err
	}

	err = c.call(metrics.ShardDistributorStoreRecordShardStatisticsBatchScope, op, metrics.NamespaceTag(namespace))
	return
}

func (c *meteredStore) ResetNamespace(ctx context.Context, namespace string) (i1 int64, err error) {
	op := func() error {
		i1, err = c.wrapped.ResetNamespace(ctx, namespace)
		return err
	}

	err = c.call(metrics.ShardDistributorStoreResetNamespaceScope, op, metrics.NamespaceTag(namespace))
	return
}

func (c *meteredStore) SubscribeToExecutorStatusChanges(ctx context.Context, namespace string) (ch1 <-chan int64, err error) {
	op := func() error {
		ch1, err = c.wrapped.SubscribeToExecutorStatusChanges(ctx, namespace)
		return err
	}

	err = c.call(metrics.ShardDistributorStoreSubscribeToExecutorStatusChangesScope, op, metrics.NamespaceTag(namespace))
	return
}

func (c *meteredStore) SubscribeToNamespaceChanges(namespace string) (ch1 <-chan struct {
}, err error) {
	return c.wrapped.SubscribeToNamespaceChanges(namespace)
}

func (c *meteredStore) UndrainHosts(ctx context.Context, namespace string, hostnames []string) (sa1 []string, err error) {
	op := func() error {
		sa1, err = c.wrapped.UndrainHosts(ctx, namespace, hostnames)
		return err
	}

	err = c.call(metrics.ShardDistributorStoreUndrainHostsScope, op, metrics.NamespaceTag(namespace))
	return
}

func (c *meteredStore) UndrainShards(ctx context.Context, namespace string, shardIDs []string) (sa1 []string, err error) {
	op := func() error {
		sa1, err = c.wrapped.UndrainShards(ctx, namespace, shardIDs)
		return err
	}

	err = c.call(metrics.ShardDistributorStoreUndrainShardsScope, op, metrics.NamespaceTag(namespace))
	return
}
