// Code generated by MockGen. DO NOT EDIT.
// Source: factory.go
//
// Generated by this command:
//
//	mockgen -package smctl -source factory.go -destination factory_mock.go -self_package github.com/cadence-workflow/shard-manager/tools/smctl
//

// Package smctl is a generated GoMock package.
package smctl

import (
	reflect "reflect"

	cli "github.com/urfave/cli/v3"
	gomock "go.uber.org/mock/gomock"

	sharddistributor "github.com/cadence-workflow/shard-manager/client/sharddistributor"
)

// MockClientFactory is a mock of ClientFactory interface.
type MockClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockClientFactoryMockRecorder
	isgomock struct{}
}

// MockClientFactoryMockRecorder is the mock recorder for MockClientFactory.
type MockClientFactoryMockRecorder struct {
	mock *MockClientFactory
}

// NewMockClientFactory creates a new mock instance.
func NewMockClientFactory(ctrl *gomock.Controller) *MockClientFactory {
	mock := &MockClientFactory{ctrl: ctrl}
	mock.recorder = &MockClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientFactory) EXPECT() *MockClientFactoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClientFactory) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientFactoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClientFactory)(nil).Close))
}

// ShardManagerClient mocks base method.
func (m *MockClientFactory) ShardManagerClient(cmd *cli.Command) (sharddistributor.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShardManagerClient", cmd)
	ret0, _ := ret[0].(sharddistributor.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShardManagerClient indicates an expected call of ShardManagerClient.
func (mr *MockClientFactoryMockRecorder) ShardManagerClient(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShardManagerClient", reflect.TypeOf((*MockClientFactory)(nil).ShardManagerClient), cmd)
}
