package metered

// Code generated by gowrap. DO NOT EDIT.
// template: ../../templates/metered.tmpl
// gowrap: http://github.com/hexdigest/gowrap

import (
	"context"

	"github.com/cadence-workflow/shard-manager/common/log"
	"github.com/cadence-workflow/shard-manager/common/log/tag"
	"github.com/cadence-workflow/shard-manager/common/metrics"
	"github.com/cadence-workflow/shard-manager/common/types"
	"github.com/cadence-workflow/shard-manager/service/sharddistributor/handler"
)

type metricsHandler struct {
	handler       handler.Handler
	logger        log.Logger
	metricsClient metrics.Client
}

func NewMetricsHandler(handler handler.Handler, logger log.Logger, metricsClient metrics.Client) handler.Handler {
	return &metricsHandler{
		handler:       handler,
		logger:        logger,
		metricsClient: metricsClient,
	}
}

func (h *metricsHandler) GetNamespaceState(ctx context.Context, gp1 *types.GetNamespaceStateRequest) (gp2 *types.GetNamespaceStateResponse, err error) {
	defer func() { log.CapturePanic(recover(), h.logger, &err) }()

	scope := h.metricsClient.Scope(metrics.ShardDistributorGetNamespaceStateScope)
	scope = scope.Tagged(metrics.NamespaceTag(gp1.GetNamespace()))
	scope.IncCounter(metrics.ShardDistributorRequests)
	sw := scope.StartTimer(metrics.ShardDistributorLatency)
	defer sw.Stop()
	logger := h.logger.WithTags(tag.ShardNamespace(gp1.GetNamespace()))

	gp2, err = h.handler.GetNamespaceState(ctx, gp1)

	if err != nil {
		handleErr(err, scope, logger)
	}

	return gp2, err
}

func (h *metricsHandler) GetShardOwner(ctx context.Context, gp1 *types.GetShardOwnerRequest) (gp2 *types.GetShardOwnerResponse, err error) {
	defer func() { log.CapturePanic(recover(), h.logger, &err) }()

	scope := h.metricsClient.Scope(metrics.ShardDistributorGetShardOwnerScope)
	scope = scope.Tagged(metrics.NamespaceTag(gp1.GetNamespace()))
	scope.IncCounter(metrics.ShardDistributorRequests)
	sw := scope.StartTimer(metrics.ShardDistributorLatency)
	defer sw.Stop()
	logger := h.logger.WithTags(tag.ShardNamespace(gp1.GetNamespace()))

	gp2, err = h.handler.GetShardOwner(ctx, gp1)

	if err != nil {
		handleErr(err, scope, logger)
	}

	return gp2, err
}

func (h *metricsHandler) Health(ctx context.Context) (hp1 *types.HealthStatus, err error) {
	return h.handler.Health(ctx)
}

func (h *metricsHandler) InspectShard(ctx context.Context, gp1 *types.GetShardOwnerRequest) (gp2 *types.GetShardOwnerResponse, err error) {
	defer func() { log.CapturePanic(recover(), h.logger, &err) }()

	scope := h.metricsClient.Scope(metrics.ShardDistributorInspectShardScope)
	scope = scope.Tagged(metrics.NamespaceTag(gp1.GetNamespace()))
	scope.IncCounter(metrics.ShardDistributorRequests)
	sw := scope.StartTimer(metrics.ShardDistributorLatency)
	defer sw.Stop()
	logger := h.logger.WithTags(tag.ShardNamespace(gp1.GetNamespace()))

	gp2, err = h.handler.InspectShard(ctx, gp1)

	if err != nil {
		handleErr(err, scope, logger)
	}

	return gp2, err
}

func (h *metricsHandler) ListNamespaces(ctx context.Context, lp1 *types.ListNamespacesRequest) (lp2 *types.ListNamespacesResponse, err error) {
	defer func() { log.CapturePanic(recover(), h.logger, &err) }()

	scope := h.metricsClient.Scope(metrics.ShardDistributorListNamespacesScope)
	scope = scope.Tagged(metrics.NamespaceTag(lp1.GetNamespace()))
	scope.IncCounter(metrics.ShardDistributorRequests)
	sw := scope.StartTimer(metrics.ShardDistributorLatency)
	defer sw.Stop()
	logger := h.logger.WithTags(tag.ShardNamespace(lp1.GetNamespace()))

	lp2, err = h.handler.ListNamespaces(ctx, lp1)

	if err != nil {
		handleErr(err, scope, logger)
	}

	return lp2, err
}

func (h *metricsHandler) Start() {
	h.handler.Start()
	return
}

func (h *metricsHandler) Stop() {
	h.handler.Stop()
	return
}

func (h *metricsHandler) WatchNamespaceState(wp1 *types.WatchNamespaceStateRequest, w1 handler.WatchNamespaceStateServer) (err error) {
	defer func() { log.CapturePanic(recover(), h.logger, &err) }()

	scope := h.metricsClient.Scope(metrics.ShardDistributorWatchNamespaceStateScope)
	scope = scope.Tagged(metrics.NamespaceTag(wp1.GetNamespace()))
	scope.IncCounter(metrics.ShardDistributorRequests)
	sw := scope.StartTimer(metrics.ShardDistributorLatency)
	defer sw.Stop()
	logger := h.logger.WithTags(tag.ShardNamespace(wp1.GetNamespace()))

	err = h.handler.WatchNamespaceState(wp1, w1)

	if err != nil {
		handleErr(err, scope, logger)
	}

	return err
}
