// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -package store -source store.go -destination=store_mock.go Store
//

// Package store is a generated GoMock package.
package store

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTxn is a mock of Txn interface.
type MockTxn struct {
	ctrl     *gomock.Controller
	recorder *MockTxnMockRecorder
	isgomock struct{}
}

// MockTxnMockRecorder is the mock recorder for MockTxn.
type MockTxnMockRecorder struct {
	mock *MockTxn
}

// NewMockTxn creates a new mock instance.
func NewMockTxn(ctrl *gomock.Controller) *MockTxn {
	mock := &MockTxn{ctrl: ctrl}
	mock.recorder = &MockTxnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxn) EXPECT() *MockTxnMockRecorder {
	return m.recorder
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AssignShards mocks base method.
func (m *MockStore) AssignShards(ctx context.Context, namespace string, request AssignShardsRequest, guard GuardFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignShards", ctx, namespace, request, guard)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignShards indicates an expected call of AssignShards.
func (mr *MockStoreMockRecorder) AssignShards(ctx, namespace, request, guard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignShards", reflect.TypeOf((*MockStore)(nil).AssignShards), ctx, namespace, request, guard)
}

// DeleteAssignedStates mocks base method.
func (m *MockStore) DeleteAssignedStates(ctx context.Context, namespace string, executorIDs []string, guard GuardFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAssignedStates", ctx, namespace, executorIDs, guard)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAssignedStates indicates an expected call of DeleteAssignedStates.
func (mr *MockStoreMockRecorder) DeleteAssignedStates(ctx, namespace, executorIDs, guard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAssignedStates", reflect.TypeOf((*MockStore)(nil).DeleteAssignedStates), ctx, namespace, executorIDs, guard)
}

// DeleteExecutors mocks base method.
func (m *MockStore) DeleteExecutors(ctx context.Context, namespace string, executorIDs []string, guard GuardFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExecutors", ctx, namespace, executorIDs, guard)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExecutors indicates an expected call of DeleteExecutors.
func (mr *MockStoreMockRecorder) DeleteExecutors(ctx, namespace, executorIDs, guard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExecutors", reflect.TypeOf((*MockStore)(nil).DeleteExecutors), ctx, namespace, executorIDs, guard)
}

// DeleteShardStats mocks base method.
func (m *MockStore) DeleteShardStats(ctx context.Context, namespace string, shardIDs []string, guard GuardFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteShardStats", ctx, namespace, shardIDs, guard)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteShardStats indicates an expected call of DeleteShardStats.
func (mr *MockStoreMockRecorder) DeleteShardStats(ctx, namespace, shardIDs, guard any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteShardStats", reflect.TypeOf((*MockStore)(nil).DeleteShardStats), ctx, namespace, shardIDs, guard)
}

// DrainHosts mocks base method.
func (m *MockStore) DrainHosts(ctx context.Context, namespace string, hosts []DrainedHost) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DrainHosts", ctx, namespace, hosts)
	ret0, _ := ret[0].(error)
	return ret0
}

// DrainHosts indicates an expected call of DrainHosts.
func (mr *MockStoreMockRecorder) DrainHosts(ctx, namespace, hosts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrainHosts", reflect.TypeOf((*MockStore)(nil).DrainHosts), ctx, namespace, hosts)
}

// DrainShards mocks base method.
func (m *MockStore) DrainShards(ctx context.Context, namespace string, shardIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DrainShards", ctx, namespace, shardIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DrainShards indicates an expected call of DrainShards.
func (mr *MockStoreMockRecorder) DrainShards(ctx, namespace, shardIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrainShards", reflect.TypeOf((*MockStore)(nil).DrainShards), ctx, namespace, shardIDs)
}

// GetDrainedHosts mocks base method.
func (m *MockStore) GetDrainedHosts(ctx context.Context, namespace string) ([]DrainedHost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDrainedHosts", ctx, namespace)
	ret0, _ := ret[0].([]DrainedHost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDrainedHosts indicates an expected call of GetDrainedHosts.
func (mr *MockStoreMockRecorder) GetDrainedHosts(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDrainedHosts", reflect.TypeOf((*MockStore)(nil).GetDrainedHosts), ctx, namespace)
}

// GetDrainedShards mocks base method.
func (m *MockStore) GetDrainedShards(ctx context.Context, namespace string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDrainedShards", ctx, namespace)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDrainedShards indicates an expected call of GetDrainedShards.
func (mr *MockStoreMockRecorder) GetDrainedShards(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDrainedShards", reflect.TypeOf((*MockStore)(nil).GetDrainedShards), ctx, namespace)
}

// GetExecutorState mocks base method.
func (m *MockStore) GetExecutorState(ctx context.Context, namespace, executorID string) (ExecutorState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutorState", ctx, namespace, executorID)
	ret0, _ := ret[0].(ExecutorState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecutorState indicates an expected call of GetExecutorState.
func (mr *MockStoreMockRecorder) GetExecutorState(ctx, namespace, executorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutorState", reflect.TypeOf((*MockStore)(nil).GetExecutorState), ctx, namespace, executorID)
}

// GetState mocks base method.
func (m *MockStore) GetState(ctx context.Context, namespace string) (*NamespaceState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState", ctx, namespace)
	ret0, _ := ret[0].(*NamespaceState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetState indicates an expected call of GetState.
func (mr *MockStoreMockRecorder) GetState(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockStore)(nil).GetState), ctx, namespace)
}

// RecordHeartbeat mocks base method.
func (m *MockStore) RecordHeartbeat(ctx context.Context, namespace, executorID string, state HeartbeatState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordHeartbeat", ctx, namespace, executorID, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordHeartbeat indicates an expected call of RecordHeartbeat.
func (mr *MockStoreMockRecorder) RecordHeartbeat(ctx, namespace, executorID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordHeartbeat", reflect.TypeOf((*MockStore)(nil).RecordHeartbeat), ctx, namespace, executorID, state)
}

// RecordShardStatistics mocks base method.
func (m *MockStore) RecordShardStatistics(ctx context.Context, namespace, executorID string, assignmentModRevision int64, statistics map[string]ShardStatistics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordShardStatistics", ctx, namespace, executorID, assignmentModRevision, statistics)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordShardStatistics indicates an expected call of RecordShardStatistics.
func (mr *MockStoreMockRecorder) RecordShardStatistics(ctx, namespace, executorID, assignmentModRevision, statistics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordShardStatistics", reflect.TypeOf((*MockStore)(nil).RecordShardStatistics), ctx, namespace, executorID, assignmentModRevision, statistics)
}

// RecordShardStatisticsBatch mocks base method.
func (m *MockStore) RecordShardStatisticsBatch(ctx context.Context, namespace string, updates []ExecutorShardStatistics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordShardStatisticsBatch", ctx, namespace, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordShardStatisticsBatch indicates an expected call of RecordShardStatisticsBatch.
func (mr *MockStoreMockRecorder) RecordShardStatisticsBatch(ctx, namespace, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordShardStatisticsBatch", reflect.TypeOf((*MockStore)(nil).RecordShardStatisticsBatch), ctx, namespace, updates)
}

// ResetNamespace mocks base method.
func (m *MockStore) ResetNamespace(ctx context.Context, namespace string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetNamespace", ctx, namespace)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetNamespace indicates an expected call of ResetNamespace.
func (mr *MockStoreMockRecorder) ResetNamespace(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetNamespace", reflect.TypeOf((*MockStore)(nil).ResetNamespace), ctx, namespace)
}

// SubscribeToExecutorStatusChanges mocks base method.
func (m *MockStore) SubscribeToExecutorStatusChanges(ctx context.Context, namespace string) (<-chan int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToExecutorStatusChanges", ctx, namespace)
	ret0, _ := ret[0].(<-chan int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToExecutorStatusChanges indicates an expected call of SubscribeToExecutorStatusChanges.
func (mr *MockStoreMockRecorder) SubscribeToExecutorStatusChanges(ctx, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToExecutorStatusChanges", reflect.TypeOf((*MockStore)(nil).SubscribeToExecutorStatusChanges), ctx, namespace)
}

// SubscribeToNamespaceChanges mocks base method.
func (m *MockStore) SubscribeToNamespaceChanges(namespace string) (<-chan struct{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToNamespaceChanges", namespace)
	ret0, _ := ret[0].(<-chan struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToNamespaceChanges indicates an expected call of SubscribeToNamespaceChanges.
func (mr *MockStoreMockRecorder) SubscribeToNamespaceChanges(namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToNamespaceChanges", reflect.TypeOf((*MockStore)(nil).SubscribeToNamespaceChanges), namespace)
}

// UndrainHosts mocks base method.
func (m *MockStore) UndrainHosts(ctx context.Context, namespace string, hostnames []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UndrainHosts", ctx, namespace, hostnames)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UndrainHosts indicates an expected call of UndrainHosts.
func (mr *MockStoreMockRecorder) UndrainHosts(ctx, namespace, hostnames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UndrainHosts", reflect.TypeOf((*MockStore)(nil).UndrainHosts), ctx, namespace, hostnames)
}

// UndrainShards mocks base method.
func (m *MockStore) UndrainShards(ctx context.Context, namespace string, shardIDs []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UndrainShards", ctx, namespace, shardIDs)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UndrainShards indicates an expected call of UndrainShards.
func (mr *MockStoreMockRecorder) UndrainShards(ctx, namespace, shardIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UndrainShards", reflect.TypeOf((*MockStore)(nil).UndrainShards), ctx, namespace, shardIDs)
}
